### ISSUE TITLE
Faye-websocker fails with rainbows

### ISSUE THREAD

**Issue by michelson** [faye/faye-websocket-ruby#109]
Hi Guys, we are updating a web app to rails 5, we have EventSource messages with the Faye.-websocket support, in development is working with thin, unicorn and rainbows, but on production environment we get an error from rainbows web server.

### production:
```
INFO -- : Rainbows! EventMachine worker_connections=100
I, [2017-10-16T21:37:07.715950 #29730]  INFO -- : EventMachine: epoll=true kqueue=false
terminate called after throwing an instance of 'std::runtime_error'
  what():  adding existing descriptor
```

### development:
is an error similar to: https://github.com/rails/rails/issues/22676

we are using the following versions 
+ rainbows-5.1.1
+ faye-websocket-0.10.7

our config is:

### config.ru
```ruby
    Faye::WebSocket.load_adapter('rainbows')
    run EventSockets
```

### events.rb

https://gist.github.com/michelson/ddfc9916ed07c98393406b6f4e894de9

**Comment by jcoglan** [comment]
If you're running version 4.5 or later of Rainbows, you should remove the line `Faye::WebSocket.load_adapter('rainbows')` from your config.
