### ISSUE TITLE
How to send authorization header (Authorization: Bearer token)

### ISSUE THREAD

**Issue by Seralto** [faye/faye-websocket-ruby#113]
I'm trying to send authorization token with no success:

`  ws = Faye::WebSocket::Client.new(
    url,
    protocol,
    headers: { 'Authorization' => "Bearer #{token}" }
  )`

It gives me the log:

`[:error, "Error during WebSocket handshake: Unexpected response code: 401"]`

How can I send the token?

**Comment by Seralto** [comment]
I solved the problem using `Basic Authorization`.

**Comment by brenoperucchi** [comment]
How you solved this?

**Comment by decado87** [comment]
I have same problem. When adding Headers when creating client. headers in created client are blank. doing it like this:
`ws = Faye::WebSocket::Client.new('wss://xxx.yyy.com/api/graphql',
                                     [],
                                     { :headers => { 'Authorization' => 'Bearer xyz',
                                                     'x-tenant' => 'aaa-bbb-ccc' }})`

**Comment by jcoglan** [comment]
@decado87 If I run this code, replacing the URL with `ws://localhost:3000/` and run a server using the command `nc -kl 3000`, then it prints the following:

```
GET / HTTP/1.1
Host: localhost:3000
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: JYhvzUFEjNbbcmzflbS/eQ==
Sec-WebSocket-Version: 13
Authorization: Bearer xyz
x-tenant: aaa-bbb-ccc
```

The headers are being sent by client. The most likely problems in your situation is that the TLS connection required to set up a `wss:` socket fails, or the server rejects the request. You'd have to listen to the `:error` event to determine what kind of problem is happening in your case.

**Comment by decado87** [comment]
@jcoglan im sorry for late response. didnt notice you write to me. i have postponed this issue in my work but it comes back again :)  when i added error, i've got message:
"Error during WebSocket handshake: Unexpected response code: 400"

**Comment by decado87** [comment]
now i moved forward. there is no longer error but it close immediately connection. [:close, 1002, ""]
ws.header = {"server"=>"nginx/1.18.0 (Ubuntu)", "date"=>"Mon, 12 Jul 2021 14:52:38 GMT", "connection"=>"upgrade", "upgrade"=>"websocket", "sec-websocket-accept"=>"kLdg+WT94+9fnCpW4d2RFd9qT5c=", "sec-websocket-protocol"=>"wss"}

**Comment by jcoglan** [comment]
@decado87 That `header` value is the response from the server, not the client's request headers. You shouldn't expect to see an `Authorization` header there.

The `1002` error code indicates a protocol error. That and the fact that the connection is being terminated early suggest that nginx has not been correctly configured to act as a WebSocket proxy. I would verify that you're able to establish a WebSocket connection with the original application server first, and then introduce nginx once you've got that working.

**Comment by decado87** [comment]
@jcoglan thank you for your answer. curious is that i can connect with ws client in python but in ruby i have this problem. but in python im using WebSocketTransport with url and init_payload with authorization.
i have found similar problem solved with adding option {transports: ['websocket']}
https://stackoverflow.com/questions/41381444/websocket-connection-failed-error-during-websocket-handshake-unexpected-respon
is it possible in this gem?

**Comment by decado87** [comment]
it looks like this in python:
` transport = WebsocketsTransport(url=f"wss://xxx.yyy.zzz.com/api/graphql",
                                    init_payload={
                                        "authorization": f"bearer {token}",
                                        "x-tenant": id,
                                    })

    client = Client(transport=transport, fetch_schema_from_transport=True)`
