### ISSUE TITLE
Doubt about a pub/sub implementation?

### ISSUE THREAD

**Issue by lfv89** [faye/faye-websocket-ruby#114]
I'm trying to implement a pub/sub mechanism, but am specifically having trouble implementing a `channel` feature, and I can't find any API to help me...

AFAIK, a `channel` is an abstraction that is not present by default in the WS specification... Could you help me implement such a thing over this gem? 

Any guidance would be much appreciated.

Thanks.

**Comment by jcoglan** [comment]
The abstraction provided by WebSocket is a single stream of discrete messages. There are no channels or other multiplexing functionality within the protocol itself.

Pub/sub messaging products can be built on top of it, indeed this library was extracted from one of them: https://faye.jcoglan.com/
