### ISSUE TITLE
Allow self-signed certificates with property or env variable

### ISSUE THREAD

**Issue by germanattanasio** [faye/faye-websocket-ruby#115]
Hi team,

I'm currently using this library in the [IBM Ruby sdk](https://github.com/watson-developer-cloud/ruby-sdk). It's working great so far so thank you. 👌

Recently, we found that we can't disable self-signed certificates. Some of our websockets connections need to be done using a `wss`, but the server doesn't have a valid certificate.

I looked in the README and the closed issues, and I couldn't find an issue related to this. 
Is there a parameter to turn this validation off? 
Would you be willing to add one? 

I'm happy with writing a PR if you are ok with this.

**Comment by mediumTaj** [comment]
Any update on this?

**Comment by jcoglan** [comment]
Hi there, I am not comfortable engaging with or doing work on behalf of your employer, and will not be entering into this issue any further.
