### ISSUE TITLE
Question: immediately send message with long running job

### ISSUE THREAD

**Issue by jinn999** [faye/faye-websocket-ruby#120]
Hi, I'm currently struggling to understand how to send immediately a message, without having to wait for the message block to complete.
My case is: 
Suppose I have this:
```
def long_proc
  sleep 5
end
```
and this manager:
```
  ws.onmessage = lambda do |event|
      ws.send(Time.now.to_s)
      long_proc
      ws.send(Time.now.to_s)
    end
```
And on the client side:
```
  ws.on :message do |event|
    p [:message, event.data, Time.now]
  end
```
If I run it, I get 
```
[:message, "2019-12-12 12:01:09 +0100", 2019-12-12 12:01:14 +0100]
[:message, "2019-12-12 12:01:14 +0100", 2019-12-12 12:01:14 +0100]
```
And i receive them both after the completion of the on-message block of the client.

 Is there any way that i missed to immediately send the message (i.e: so that the first message time.now in the client is equal to 12:01:09, not 14?

**Comment by craysiii** [comment]
Not the cleanest solution, but I implemented a message queue and have a separate Periodic Timer from eventmachine pop and send the messages.

**Comment by jcoglan** [comment]
This library is based on EventMachine, in which all I/O is asynchronous and the interface to the system is a single-threaded event loop. If you put a `sleep` in the middle of your code,  that blocks the current thread, so any I/O you've tried to do on the current turn of the event loop gets delayed.

The solution is to use EM's own delay methods like `add_timer`, or if you have long-running blocking workloads, move them into another thread where they won't block the reactor loop.

**Comment by jcoglan** [comment]
@jinn999 did my comment above solve your problem? Can I close this issue?

**Comment by jcoglan** [comment]
I'm going to close this as I've no further feedback, but if you need to discuss this further then please re-open it :)

**Comment by pudiva** [comment]
Hiiii!!1 👋

I just reached this page after much frustration. It would be really cool to have a paved path for this on the README.md.

Thanks ✨
