### ISSUE TITLE
Client closes with 1006 immediately upon start

### ISSUE THREAD

**Issue by jahio** [faye/faye-websocket-ruby#124]
I don't know if this is a bug or an oversight on my part since I'm pretty new to websocket programming, but I'm running a very simple EM::Websocket server (which works fine with https://github.com/hashrocket/ws), but using faye-websocket-ruby, it looks like the _client_ is closing the connection immediately and giving me error 1006, which I understand is the client closing for abnormal conditions. Using pry I was unable to find any explanation when looking at the connection or event objects.

This screenshot shows the server running fine, and the `ws` CLI client working with it fine, but the faye-websocket-ruby client just bails out as described above:

<img width="2032" alt="Screen Shot 2020-05-25 at 2 11 56 PM" src="https://user-images.githubusercontent.com/421850/82841134-274d1b80-9e92-11ea-8c63-4f7eda38f5ad.png">

```ruby
# server.rb

require 'em-websocket'

EM.run {
  EM::WebSocket.run(:host => "0.0.0.0", :port => 9090) do |ws|
    ws.onopen { |handshake|
      puts "WebSocket connection open"

      # Access properties on the EM::WebSocket::Handshake object, e.g.
      # path, query_string, origin, headers

      # Publish message to the client
      ws.send "Hello Client, you connected to #{handshake.path}"
    }

    ws.onclose { puts "Connection closed" }

    ws.onmessage { |msg|
      puts "Recieved message: #{msg}"
      ws.send "Pong: #{msg}"
    }
  end
}
```

```ruby
# client (agent.rb)

require 'faye/websocket'
require 'eventmachine'

EM.run {
  ws = Faye::WebSocket::Client.new('ws://localhost:9090')

  ws.on :open do |event|
    p [:open]
    # ws.send('Hello, world!')
  end

  ws.on :message do |event|
    p [:message, event.data]
  end

  ws.on :close do |event|
    p [:close, event.code, event.reason]
    ws = nil
  end
}
```

Any ideas what may be going on here? Thank you for your help!

**Comment by jcoglan** [comment]
These examples worked for me after I made the following changes:

- In `server.rb`:
  - replace `EM::WebSocket.run` with `EM::WebSocket.start` (their docs are incorrect)
  - remove the `handshake.path` expression from the message; `handshake` is nil and this crashes the server
- In `client.rb`:
  - replace `localhost` with `0.0.0.0`, which is the address the server is listening on

**Comment by jahio** [comment]
Thanks for your response, @jcoglan. I appreciate the info!
