### ISSUE TITLE
Faye::WebSocket::Client Does Not Appear to be Including Sec-WebSocket-Extensions in HTTP Request

### ISSUE THREAD

**Issue by ninp0** [faye/faye-websocket-ruby#136]
Here's the relevant snippet of code to connect to the remote WebSocket server:
```
require 'faye/websocket'
require 'websocket/extensions'
require 'permessage_deflate'

ws_feed = '<redacted>'

extensions = [PermessageDeflate]
         
ws = Faye::WebSocket::Client.new(
  ws_feed,
  [],
  extensions: extensions,
  ping: 9
)
```

The connection occurs successfully, resulting in an HTTP 101 (Switching Protocols) response, however the HTTP GET request does not appear to be setting the HTTP `Sec-WebSocket-Extensions` header appropriately:
```
GET / HTTP/1.1
Host: <redacted>
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: <redacted>
Sec-WebSocket-Version: 13
```

Gemfile:
```
gem 'faye-websocket', '0.11.1'
gem 'permessage_deflate', '0.1.4'
gem 'websocket-extensions', '0.1.5'
```

I would expect to see `Sec-WebSocket-Extensions: permessage-deflate` in the HTTP GET request in addition to what's listed above...what am I missing?  Thanks in advance for any assistance you can provide.

**Comment by jcoglan** [comment]
When I run this example and make it connect to a server running using `nc`, the server prints:

```
GET / HTTP/1.1
Host: 127.0.0.1:7000
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 5b3Ko4yBkQtT8Yg0YOqQ8w==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

**Comment by ninp0** [comment]
Hmmm, perhaps I just not seeing the header when verifying w/ a MITM proxy?  Here's the code to connect through a MITM proxy (e.g. BurpSuite, ZAP, etc):

```
require 'faye/websocket'
require 'websocket/extensions'
require 'permessage_deflate'

ws_feed = '<redacted>'

tls_opts = { verify_peer: false }
proxy_opts = { origin: 'http://127.0.0.1:8080' }
extensions = [PermessageDeflate]
         
ws = Faye::WebSocket::Client.new(
  ws_feed,
  [],
  tls: tls_opts,
  proxy: proxy_opts,
  extensions: extensions,
  ping: 9
)
```

**Comment by ninp0** [comment]
Argh!  Yep, default proxy setting - Thank you for your quick reply @jcoglan:

![Screenshot_2022-12-16_15-48-11](https://user-images.githubusercontent.com/1008583/208201592-a6fdc6af-abd8-4108-92d2-222e73d474c2.png)
