### ISSUE TITLE
Closing a connection blocks the event machine

### ISSUE THREAD

**Issue by aurangzaib-danial** [faye/faye-websocket-ruby#139]
I'm having a problem where if a web socket connection is closed while inside of a thread then the event machine blocks for around 30 seconds and becomes unable to send messages to other connections until it frees up. I'm unable to share my code but please have a look at this example.

```ruby
require 'faye/websocket'

App = lambda do |env|
  if Faye::WebSocket.websocket?(env)
    ws = Faye::WebSocket.new(env)

    ws.on :message do |event|
      if (event.data == 'close')
        Thread.new { ws.close }
      else
        ws.send(event.data)
      end
    end

    # Return async Rack response for keeping connection open
    ws.rack_response

  else
    # Normal HTTP request
    [200, { 'Content-Type' => 'text/plain' }, ['Please make a websocket connection']]
  end
end
```

This is just a simple echo server. If the client sends a close message then we close the connection which blocks the EM for a period of time. This is a silly example but I hope it gets the point across. This only happens when `ws.close` is called inside a thread. In my actual code, a thread calls `ws.close` once it is done doing its stuff. I cannot use event machine for the things that I'm doing in the thread. 

I'm using puma for starting up this server.

**Comment by jcoglan** [comment]
This library's API is not thread-safe; it assumes it will always be invoked on the EventMachine reactor thread. You can accomplish this by running `EM.next_tick { ws.close }`.

**Comment by jcoglan** [comment]
Alternatively, if EventMachine is proving too much of a problem, I would suggest using https://github.com/faye/websocket-driver-ruby. This provides all the protocol logic but leaves the choice of socket I/O and concurrency library up to you. `faye-websocket` is basically a thin wrapper around `websocket-driver` and EventMachine plus some hacks to make sockets work on various app servers.

**Comment by aurangzaib-danial** [comment]
Using `EM.next_tick { ws.close }` solved the problem. Super grateful for your help!
