### ISSUE TITLE
Client doesn't connect

### ISSUE THREAD

**Issue by aurangzaib-danial** [faye/faye-websocket-ruby#140]
I'm trying to connect to my faye websocket server with the faye client but it doesn't connect. I'm using following code:

```ruby
EM.run {
  ws = Faye::WebSocket::Client.new('ws://localhost:9292')

  ws.on :open do |event|
    p [:open]
    ws.send('Hello, world!')
  end

  ws.on :message do |event|
    p [:message, event.data]
  end

  ws.on :close do |event|
    p [:close, event.code, event.reason]
    ws = nil
  end
}
```

Above code prints a 1006 code but no reason. The server is running and I'm able to connect to it using my browser. My ruby version is 3.2.2. I also tried 3.0.2 but still didn't work. I also checked `event.message` and it returns `Errno::ECONNREFUSED`. Is there something I'm missing?

**Comment by jcoglan** [comment]
One thing I run into quite often with Ruby stuff is problems with how things interpret `localhost`. Some things will resolve it to `127.0.0.1` i.e. just the loopback interface, while others use `0.0.0.0` i.e. any interface on the local machine. I sometimes need to use one of these IP addresses in place of `localhost` to make things work.

**Comment by aurangzaib-danial** [comment]
Thank you so much! This is so weird. Gave me a headache for no reason.
