### ISSUE TITLE
Unable to connect to wss server using TLSv1 or greater

### ISSUE THREAD

**Issue by jcoglan** [faye/faye-websocket-ruby#39]
Moving https://github.com/faye/websocket-driver-ruby/issues/14 to this repo where it belongs. /cc @laphlaw.

> I am unable to connect to a wss (secure websocket) server.
> 
> Using ssldump to debug on the server side, I see my client (using your gem) attempt to connect using SSLv2:
> 
> 1 1 0.0048 (0.0048) C>S SSLv2 compatible client hello
> Version 3.3
> 
> Is there a way I can specify the TLS version I want to use? The server requires TLSv1 and above.

**Comment by richardc** [comment]
I just bumped into this, it's still something of a problem, but one that will in part need to be fixed in eventmachine with https://github.com/eventmachine/eventmachine/issues/603
