### ISSUE TITLE
How to use Secure-WebSockets (wss://)?

### ISSUE THREAD

**Issue by sebastianzillessen** [faye/faye-websocket-ruby#40]
I need some advice how to use secure web sockets (`wss://`)  with faye-websockets. 

I need this for two reasons:
1) 3G connections do sometimes drop none-secure connections (see http://stackoverflow.com/questions/5557776/websockets-over-a-3g-connection)
2) Security reasons

Can anyone help?
 Thanks!

**Comment by trickymuffin** [comment]
Hi, I'm trying to use it as you said but I'm having an error,  'std::runtime_error' what(): Encryption not available on this event-machine.

ws = Faye::WebSokect::Client.new('wss://localhost:8080/websocket')

Thanks a lot!

**Comment by 4rne** [comment]
I just had this problem, when trying to use a minimal docker container (ruby:3-alpine). It was missing the package `openssl-dev`. After installing that dependency everything worked for me.
