### ISSUE TITLE
rack "only partial hijack is supported"

### ISSUE THREAD

**Issue by donpdonp** [faye/faye-websocket-ruby#56]
Using rack 1.6.0 with faye-websocket 0.9.2 throws
[2015-01-24 17:06:08] ERROR NotImplementedError: only partial hijack is supported.
	/home/donp/code/cointhink/octofx/gems/ruby/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:77:in `block in service'

```ruby
if Faye::WebSocket.websocket?(env)
  ws = Faye::WebSocket.new(env)
````

which comes from
https://github.com/rack/rack/blob/master/lib/rack/handler/webrick.rb#L77

but im not sure of the root cause.

**Comment by jcoglan** [comment]
The 'Rack hijack' API lets applications gain direct access to the TCP socket; if an application hijacks the connection it then has access to the TCP input/output and Rack stops indirecting this input, so the application can implement streaming protocols like WebSocket.

There are two versions of this API: full hijacking means the app takes over TCP operation before the response headers are written, whereas partial hijacking means the application only takes over after the headers are written.

faye-websocket requires full hjiacking to work, so a webserver that only supports partial hijacking cannot be used.

**Comment by donpdonp** [comment]
Thanks for the detail. I was trying to follow 
https://github.com/faye/faye-websocket-ruby#handling-websocket-connections-in-rack

so I'm a bit confused, if Webrick doesnt support full-hijack, how does the example work?

**Comment by donpdonp** [comment]
On closer inspection, I see the example doesnt use webrick at all, but plain old Rack. Thanks for this gem!

**Comment by jcoglan** [comment]
There's a section later in the docs that describes [how to run a WebSocket app with all supported servers](https://github.com/faye/faye-websocket-ruby#running-your-socket-application).

**Comment by salmagomaa** [comment]
Installing puma gem worked with me
