### ISSUE TITLE
Not throwing exceptions when inside callback

### ISSUE THREAD

**Issue by Ricardonacif** [faye/faye-websocket-ruby#57]
Hey everyone,

My Faye implementation racked upon Rails as a middleware isn't throwing exceptions when they occur inside callback's block. For example:

```ruby
ws = Faye::WebSocket.new(env, nil, {ping: KEEPALIVE_TIME })
ws.on :open do |event|
  non_existing_method #this method will doesn't exists
end
``` 
when I call the non_existing_method, it should raise an exception, but it doesn't. I already tried 
```raise 'Something' 
```but it also doesn't work. Any clues?

**Comment by jcoglan** [comment]
I can't reproduce the behaviour you're describing. I wrote this `faye.ru` file:

```rb
require 'faye/websocket'
Faye::WebSocket.load_adapter 'thin'

run -> (env) do
  ws = Faye::WebSocket.new(env, nil, ping: 5)

  ws.on :open do |event|
    p [:open, event]
    non_existing_method
  end

  ws.rack_response
end
```

And ran it using:

```
$ thin start -R faye.ru -p 3000
```

Calling `new WebSocket('ws://localhost:3000/')` from my browser causes this error, which crashes the server:

```
faye.ru:9:in `block (3 levels) in <main>': undefined local variable or method `non_existing_method' for #<Rack::Builder:0x007fcbb13a7e68> (NameError)
```

**Comment by Ricardonacif** [comment]
I could solve it by monkey patching the thread class using:

```
class << Thread
  alias old_new new

  def new(*args, &block)
    old_new(*args) do |*bargs|
      begin
        block.call(*bargs)
      rescue Exception => e
        raise if Thread.abort_on_exception ||
        Thread.current.abort_on_exception
        puts "Thread for block #{block.inspect} terminated with exception:
        #{e.message}"
        puts e.backtrace.map {|line| " #{line}"}
      end
    end
  end
end
```

**Comment by jcoglan** [comment]
If this issue is solved, can I close it?

**Comment by Ricardonacif** [comment]
Sure

**Comment by ximus** [comment]
@Ricardonacif good sleuthing, I had the same issue.
@jcoglan I was able to reproduce the error using your test case in *puma*. I also tried it in *thin*, as you did, but it does not occur in thin

I don't yet know what specific to puma is causing the error.

**Comment by raphox** [comment]
This gem use eventmachine to define callbacks.
You need to use the following code to catch the exceptions:

```ruby
# http://stackoverflow.com/a/7630650
EM.error_handler{ |e|
  puts "Error raised during event loop: #{e.message}"
}
```
