### ISSUE TITLE
Rake fails with 'cannot load such file -- rake/extensiontask'

### ISSUE THREAD

**Issue by d-snp** [faye/faye-websocket-ruby#59]
Hi, after cloning faye-websocket-ruby and running `bundle install`, rake commands fail with the following exception:

```
faye-websocket-ruby tinco$ bundle exec rake -T
rake aborted!
LoadError: cannot load such file -- rake/extensiontask
/Users/tinco/Source/faye-websocket-ruby/Rakefile:12:in `require'
/Users/tinco/Source/faye-websocket-ruby/Rakefile:12:in `<top (required)>'
/Users/tinco/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/tinco/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

Is there a dependency missing? All the specs pass if I run rspec without rake. Seems like the 'rake-compiler' gem would be missing but I'm not sure.

**Comment by jcoglan** [comment]
Sorry, I realised I should have removed `Rakefile` when I extracted it into `websocket-driver`. It contains tasks for compiling native extensions that aren't in this module any more.

Just pushed a fix.
