### ISSUE TITLE
Recommendations for Integration Testing Faye Websocket Client App

### ISSUE THREAD

**Issue by DVG** [faye/faye-websocket-ruby#62]
I'm currently building a websocket client for Slack on top of this gem, and while it works great, I wanted to create some integration tests for the high level functionality. To this end, I basically tried to make a Fake Slack Websocket Server:

```ruby
class FakeSlack
  attr_accessor :socket, :messages

  def initialize
    @messages = []
  end

  def call(env)
    if Faye::WebSocket.websocket?(env)
      self.socket = Faye::WebSocket.new(env)

      socket.on :message do |event|
        @messages << event.data
        socket.send(event.data)
      end

      socket.rack_response
    else
      [200, {'Content-Type' => 'text/plain'}, ['Hello']]
    end
  end

  def has_message?(message)
    messages.include? message
  end
end
```

The idea here being I'd hold all messages in the "chat room" in an array, and the Fake Slack would accept messages from the actual client.

Before the test suit runs, I set up the server and connect my client to it like so:

```ruby
  @slack = FakeSlack.new

  # Webmock route ws connection to FakeSlack
  stub_request(:any, "ws://localhost:9292").to_rack(@slack)

  Thread.new do
    MyApp.websocket.connect
  end
```

And this is the basic test:

```ruby
  MyApp.websocket.send_message "Some Message"
  expect(@slack).to have_message "The Response."
```

This seems to more or less work from a test set up perspective, and I can see in the log that my client gets connected to the Server, and my client sends the message to the Server. But at that point it falls apart, because the server doesn't appear to be alive. It accepts the initial connection, but doesn't react after that. So the messages array is never populated, and I can't make assertions on it. 

Do you have any recommendations for testing a client against a stand-in server?

**Comment by jcoglan** [comment]
What does `MyApp.websocket.connect` do internally? How does `stub_request` work? I would be surprised if WebMock could intercept what `Faye::Client` does, because it it doesn't use an HTTP client library, and I'd be surprised if it supported WebSocket in general.

**Comment by DVG** [comment]
So last night I raided client_spec to try and get something working, and I feel like I'm almost there, but the asyncronous stuff is tripping me up

I took most of the async steps in your client_spec and made this rspec:

```ruby
  before { server port, :thin, true }
  after  { stop }
  let(:port)  { 4180 }
  let(:url)   { "ws://localhost:#{port}"}
  it "responds with a fact" do
    connect_bot url
    send_message "factbot, fact"
    bot_listen_for_message
    sleep 1 # If I remove this then fail
    slack_listen_for_message
    chatroom_has_message "151 is the number of pokemon in the original game"
  end
```

It works! But, I have to manually sleep or the test will beat the runloop



If you wanna see the how I implemented the methods, the branch is [here](https://github.com/DVG/EDI/blob/fake-websocket/spec/features/built-in-services/fact_service_spec.rb)

**Comment by jcoglan** [comment]
I would make `bot_listen_for_message` run before `send_message`, and introduce a step that polls for receipt of the message, rather than using a timer. Timers are exceedingly brittle.

**Comment by DVG** [comment]
Thanks for the help! I ended up realizing I was having instance variable collision between the slack and bot listening for messages, once I gave them individual variables it all worked great!
