### ISSUE TITLE
Close reason and code information lost

### ISSUE THREAD

**Issue by nmj3e** [faye/faye-websocket-ruby#64]
In the begin_close procedure, in lib/faye/websocket/api.rb,  I noticed that the finalize_close procedure is being called before @close_params is being set.  This means that the references to @close_params inside finalize_close won't ever have anything but their default values, and thus the 'reason' and 'code' arguments to begin_close are information that is being lost.

**Comment by jcoglan** [comment]
It only calls `finalize_close` before setting the params, in the event that `@stream` is nil. This means the socket was either never connected initially or has already been closed. It seems that in such events the close parameters would be meaningless.

Do you have an example of when this causes surprising behaviour?

**Comment by jcoglan** [comment]
I'm ambivalent about my comment above and so if this is surprising users then I'll fix it. See b4a6c06.
