### ISSUE TITLE
Wrong number of arguments in 0.10.0

### ISSUE THREAD

**Issue by ryanstout** [faye/faye-websocket-ruby#68]
I'm seeing this issue on any of my apps that start using 0.10.0, basically, event_emitter.rb in websocket-driver line 16 is calling event_target.rb line 20, with too many arguments.

```
/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api/event_target.rb:20:in `add_listener'
/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.0/lib/websocket/driver/event_emitter.rb:16:in `on'
```

Let me know if you need more info.  Thanks for the great gem!

**Comment by willisrocks** [comment]
I'm getting this error using 0.9.2

```
/home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api/event_target.rb:20:in `add_listener': wrong number of arguments (2 for 1) (ArgumentError)
```

Funny thing is I'm only getting this error on my linux box and not on OS X. Both machines are using rbenv and ruby 2.2.2.

**Comment by jcoglan** [comment]
This is fixed in https://github.com/faye/websocket-driver-ruby/commit/75fe55eaba26d838a0038206c09e4e5637a41024.
