### ISSUE TITLE
Wrong word of passenger configuration

### ISSUE THREAD

**Issue by SmileZero** [faye/faye-websocket-ruby#70]
In Readme
https://github.com/faye/faye-websocket-ruby#running-the-app-with-passenger
Sorry, there is a wrong word in the config code and can mislead others.
```
if defined?(PhusionPasseneger)
  PhusionPassenger.advertised_concurrency_level = 0
end
```
PhusionPasseneger should be PhusionPassenger.

**Comment by jcoglan** [comment]
Fixed in #71/#75.
