### ISSUE TITLE
Secure Websocket client

### ISSUE THREAD

**Issue by trickymuffin** [faye/faye-websocket-ruby#72]
Hi, I tried to do a connection with a secure websocket server and I get the error below, any help would be much appreciated. 
 
> 'std::runtime_error' what(): Encryption not available on this event-machine This application has requested the Runtime to terminate it in an unusual way

```ruby
    require 'faye/websocket'
    require 'eventmachine'

    EM.run {
      ws = Faye::WebSocket::Client.new('wss://localhost:8080/websocket')

      ws.on :open do |event|
        p [:open]
        ws.send('Hello, world!')
      end

      ws.on :message do |event|
        p [:message, event.data]
      end

      ws.on :close do |event|
        p [:close, event.code, event.reason]
        ws = nil
      end
    }
```

Thanks in advance!

**Comment by trickymuffin** [comment]
The problem was that I was using ruby version 193 which can't deal with secure web-sockets, buy using a newer version my problem got solved (I'm using 222 now)

**Comment by trickymuffin** [comment]
I'm sorry to reopen this one but this doesn't seem to work on windows (7 64 ) some help on this would be much appreciated

**Comment by jcoglan** [comment]
I've never seen this error myself but from googling it seems to be caused by your Ruby or EventMachine not having support for crypto (e.g. by binding to openssl) compiled in. To find out if this is the case, skip WebSocket and make a TLS connection to your server and check if it connects successfully:

```rb
require 'eventmachine'

module Connection
  def connection_completed
    p :tcp_established
    start_tls
  end
end

EM.run {
  EM.connect(hostname, port, Connection)
}
```

**Comment by trickymuffin** [comment]
This error is eventmachine related and it happens only on windows, installing OpenSSL  and compiling eventmachine with it solved the problem. Thanks though and sorry for the bug, Ill be closing this as is not related to Faye websocket
