### ISSUE TITLE
emit_error error

### ISSUE THREAD

**Issue by wle-aca** [faye/faye-websocket-ruby#73]
occasionally seeing this error in our logs.
I'll see if I can track down the full trace, otherwise just letting you know in case it is obvious enough to track down the cause

```
#<NoMethodError: undefined method `>=' for nil:NilClass>
ruby/2.2.2/gems/faye-websocket-0.10.0/lib/faye/websocket/api.rb:108:in `emit_error'
```

**Comment by jcoglan** [comment]
Could you find out whether [this change](https://github.com/faye/faye-websocket-ruby/commit/df0c128460da43fa067d275fa45af7972f7f49cf) stops the error from happening?

**Comment by stakach** [comment]
Works for me! (Same organisation)

**Comment by wle-aca** [comment]
Yep, that changed fixed it. Thanks very much, the issue can be closed.
