### ISSUE TITLE
Connection drops after 75 seconds

### ISSUE THREAD

**Issue by cantino** [faye/faye-websocket-ruby#78]
I'm running into an odd issue when trying to connect to a Faye::WebSocket server from an embedded device.  I'm not sure if the issue is in this library, or the device software. We have an embedded Wifi module that manages all the Internet protocols through a command/response serial port. For a remote server that is hosting an application via a WebSocket, we command the module to open a WebSocket giving it the URL. The module then responds with a handle for the socket opened.  We then happily go along writing a stream to that handle.  In this case it's around 200 chars of JSON.  The rate is about once per second.  When I write the stream, the Wifi module responds almost immediately with "Success".  However, after the 1:16 the delay between the writing to the stream and the response of success suddenly changes from immediacy to around 2 seconds and the response changes to command failed.  The WebSocket seems to remain open at this point as indicated by a separately given command to the Wifi module that provides a list of open WebSockets.  After three such command failed responses, the query of available WebSockets indicates that the socket has closed.

Our Ruby process is incredibly vanilla:

```ruby
App = lambda do |env|
  if Faye::WebSocket.websocket?(env)
    ws = Faye::WebSocket.new(env)

    ws.on :message do |event|
      File.open(File.expand_path(File.join(File.dirname(__FILE__), 'data', 'dump.txt')), 'a') do |file|
        file.puts event.data
      end
      ws.send('received')
    end

    ws.on :close do |event|
      ws = nil
    end

    ws.on :open do |event|
    end

    ws.on :error do |event|
      p [:error, event]
    end

    ws.rack_response
  end
end
```

Do you have any ideas on how we could debug this.  Is there a default in the system that would be triggering at about 75 seconds?

Any help is much appreciated!

**Comment by jcoglan** [comment]
I can't reproduce the situation you're describing. My advice would be to check it other kinds of clients have the same problem, e.g. a client running in JS in the browser or a client implemented in Ruby on your server machine. If you have any proxies in front of the server, try bypassing those and connecting to the server directly. Eliminate moving parts until you discover which piece is causing the problem.

**Comment by cantino** [comment]
Thank you for looking into it. We think it was likely a client-side issue with not emptying the response buffer.  We'll dig in further if it happens again.
