### ISSUE TITLE
ws.on :close

### ISSUE THREAD

**Issue by a-leung** [faye/faye-websocket-ruby#79]
Just want to get some clarification on the Faye sample code:

````ruby
ws.on :close do |event|
  p [:close, event.code, event.reason]
  ws = nil
end
````

I understand this sets up callbacks for the socket when it closes.

My main question is: `ws = nil` required on the socket closing? Is `ws = nil` required for this part of the code? What if this is omitted?

**Comment by jcoglan** [comment]
It's possible that if you don't remove that reference to the socket when you're done using it, then the server will leak memory.

**Comment by a-leung** [comment]
thanks, that's what i thought too.

I'll close the issue now unless there's more info.
