### ISSUE TITLE
emit_error when passing URL without protocol

### ISSUE THREAD

**Issue by cwurm** [faye/faye-websocket-ruby#81]
Similar to https://github.com/faye/faye-websocket-ruby/issues/73 there's the same error message when passing a URL into `Faye::WebSocket::Client.new` without including the protocol, e.g. `stream.wikimedia.org/rc`.

The fix in #73 does not work for this, the reason is that `initialize` in `api.rb` gets called after initializing the driver in `client.rb`and during driver init the error `undefined method `` ` ``+' for nil:NilClass` occurs that is then swallowed.

Backtrace:
```
/Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.2/lib/websocket/driver/client.rb:20:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.2/lib/websocket/driver.rb:139:in `new'
/Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.2/lib/websocket/driver.rb:139:in `client'
/Library/Ruby/Gems/2.0.0/gems/faye-websocket-0.10.0/lib/faye/websocket/client.rb:14:in `initialize'
```

**Comment by jcoglan** [comment]
This is partly ameliorated by https://github.com/faye/websocket-driver-ruby/commit/4ae198b1d3c5343799774d9abfbc6021dc234aad which at least throws a more helpful error about the URL being invalid.

**Comment by jcoglan** [comment]
This should be fixed in https://github.com/faye/faye-websocket-ruby/commit/383dc1d64c5881bc98f309e666f22938cfbd3e96.
