### ISSUE TITLE
WS::Client fails to connect via WSS

### ISSUE THREAD

**Issue by rwz** [faye/faye-websocket-ruby#86]
I have a server running `Faye::WebSocket` on ports 80 and 443 and a client using `Faye::WebSocket::Client`.

The problem is that client works perfectly fine when using WS scheme but fails to connect to the same server via WSS. It just immediately triggers `:close` callback with empty reason and code 1006.

I specifically made sure that it's not a server issue by trying other clients. My browser and other online tools like [websocket echo test](http://www.websocket.org/echo.html) are having no trouble connecting via both WS and WSS.

**Comment by jcoglan** [comment]
I was using `Faye::WebSocket::Client` just this week to connect to a `wss:` endpoint (the Slack Realtime API). Can you provide an example of a server that it's refusing to connect to?

**Comment by rwz** [comment]
I put together a showcase app to illustrate the issue, but to my amusement it worked perfectly and connected without any trouble.

The problematic app is deployed to a brand new Heroku Spaces runtime and uses custom SSL cert, so the issue might be related to one of these things. 

I'll do more research and update the issue once I figure out what's going on.

**Comment by rwz** [comment]
In the meantime, do you have any hints about debugging `EM::Connection`? Seems like `EM::Connection#start_tls` method is the main culprit here.

**Comment by jcoglan** [comment]
I'm no expert on SSL/TLS or how EM handles it, but we might require more options to be added to pass through certs to EM, if it supports that. Please let me know if you find out anything useful.

**Comment by rwz** [comment]
Alright, I've been able to narrow down to the Heroku Spaces platform. I've notified folks responsible for the routing so I guess they'll help debugging this.

But it still seems weird that browsers connects without an issue, while `EM::Connection`is having trouble.

Also, seems like current client implementation just silently disconnects with code 1006 when there's an exception. I've noticed that it does the same when I deliberately raise a runtime error in one of the handlers. Is there a way to make it actually raise the error instead of swallowing it and just disconnecting?

**Comment by rwz** [comment]
So turns out the new platform is using SNI SSL which is not supported by eventmachine yet. Its support was added in only in version 1.2.0.dev.1. There's also an additional parameter called `sni_hostname` that needs to be passed to `start_tls` method to make it work.

I can send a PR to faye/websocket to make it forward compatible with future version of eventmachine and work with SNI out of the box. Seems like there won't be any harm from passing this param on older versions of eventmachine, since it's gonna simply ignore it.

**Comment by jcoglan** [comment]
If and when EventMachine puts SNI support in a production release, I'll happily merge support for that in here.

**Comment by jcoglan** [comment]
EventMachine 1.2 was released last month. @rwz are you able to send us a PR for whatever's needed to get SNI working in this gem?

**Comment by rwz** [comment]
I ended up ditching EventMachine and coding my own event loop around native ruby socket IO. I had a working fork for EventMachine SNI somewhere, I'll look for it and send a PR.

**Comment by jcoglan** [comment]
This is fixed in #94.
