### ISSUE TITLE
The example in the Readme fails for a generic Hijack capable server (Iodine)

### ISSUE THREAD

**Issue by boazsegev** [faye/faye-websocket-ruby#87]
Hi James,

I was trying out the example in the Readme file (the code for the `config.ru` is at the bottom) and it failed when using Thin.

The reason I was trying it out is because I'm developing a web server for my Ruby pet project ([Iodine](https://github.com/boazsegev/iodine)) and I wanted to make sure it supported Faye... after Faye websockets failed persistently, I tested Faye with Thin and Puma as well.

These are my results:

Thin (which is officially stated as supported), fails with:
`WebSocket connection to 'ws://localhost:3000/' failed: Error during WebSocket handshake: 'Upgrade' header is missing`

Iodine, fails with:
`WebSocket connection to 'ws://localhost:3000/' failed: Error during WebSocket handshake: 'Sec-WebSocket-Accept' header is missing`
(maybe a similar issue?)

Puma / Rainbows / Passenger:
Success.

This is the code I used (`config.ru`):

```ruby
require 'rack'
require 'faye/websocket'

rack_app = lambda do |env|
  if Faye::WebSocket.websocket?(env)
    ws = Faye::WebSocket.new(env)

    ws.on :message do |event|
      ws.send(event.data.to_s)
    end

    ws.on :close do |event|
      p [:close, event.code, event.reason]
      ws = nil
    end

    # Return async Rack response
    ws.rack_response

  else
    # Normal HTTP request
    [200, {'Content-Type' => 'text/plain'}, ["Hello\n"]]
  end
end

run rack_app
```

If it was only the server I was writing, I would keep looking for issues with my `hijack` implementation... however, since `thin` is also causing errors, I thought you might have a look.

**Comment by boazsegev** [comment]
Update:

I feel slightly stupid for not noticing that Thin requires a unique adapter to work...

Using `Faye::WebSocket.load_adapter('thin')` fixed the issue for thin.

Still, I would really like to support Faye on the server I'm writing (the [Iodine server](https://github.com/boazsegev/iodine), version 0.2.0, still unreleased)... but it fails even though Iodine supports (almost) every Rack requirement (except there's no callback for hijack, but isn't a feature used by Faye from what I was reading).

Could you please tell me what features my server needs to support in order to support Faye natively, without any adapters?

**Comment by jcoglan** [comment]
Supporting `rack.hijack` should be sufficient; that's what allows Passenger, Puma and Rainbows 4.5+ to work without needing adapters.

**Comment by boazsegev** [comment]
Hi James,

Thanks for taking the time to answer.

Iodine supports hijacking - once `rack.hijack` is called, Iodine returns a TCPSocket object and the response will not be processed...  But I sill get similar error headers as `thin`, and it's always the `Sec-WebSocket-Accept` header that's missing (on `thin`, it's always the `Upgrade` header)... I must be missing something.

Can you point me to the code that performs the handshake, so I can see what it's looking for?

**Comment by jcoglan** [comment]
If the server supports `async.callback` (e.g. Thin) then this code is called:

https://github.com/faye/faye-websocket-ruby/blob/master/lib/faye/websocket.rb#L78-L80

The interaction with `rack.hijack` is in this method:

https://github.com/faye/faye-websocket-ruby/blob/master/lib/faye/rack_stream.rb#L28-L51

**Comment by jcoglan** [comment]
You'll probably also find it useful to know that the driver (see the `websocket-driver` gem) is started when you call `rack_response`:

https://github.com/faye/faye-websocket-ruby/blob/master/lib/faye/websocket.rb#L83-L92

and it sends all data including the handshake response headers into this method:

https://github.com/faye/faye-websocket-ruby/blob/master/lib/faye/websocket/api.rb#L55-L57

which in turn calls:

https://github.com/faye/faye-websocket-ruby/blob/master/lib/faye/rack_stream.rb#L79-L84

**Comment by jcoglan** [comment]
Which reminds me, I'm not sure what you're goals are but you might want to consider using `websocket-driver` directly and doing the I/O stuff yourself, if that would better suit your needs.

**Comment by boazsegev** [comment]
Thanks!

I'll read through the code and see what I can dig up.

So far, I have used `telnet` to connect with the server, and sent the request:
```
GET / HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: y0eGBK40KPi4DQhEo7l02Q==
Sec-WebSocket-Version: 13
Host: localhost:3000
```

What I got was:

```
HTTP/1.1 101 Web Socket Protocol Handshake
Upgrade: WebSocket
Connection: Upgrade
WebSocket-Location: ws://localhost:3000/
```

Then the app simply waits for websocket data (the HTTP timeout is ignored since the original server doesn't hold on to the socket any longer)...

... I'm trying to figure out why I'm missing the `Sec-WebSocket-Accept` header.

As for my goals:

It started as a pet project. I wrote an HTTP & websocket server in Ruby and added a framework to go with it (plezi.io).

As it started to gain ground and performance started to matter, I rewrote the server in C (the framework is far behind) and got wonderful results (I'm getting over 30K req/sec where Puma game me ~16K for a simple Hello World rack application).

I think that if I could complete the server in a way that supports the community's most favorite gems, then I might have done something worthwhile with this pet project.

**Comment by jcoglan** [comment]
I just mention this because Iodine looks like it wants to replace EventMachine, to yield better performance, and so integrating with something that's "throttled" by EM might not get you the best yield. If you use websocket-driver and control the I/O and concurrency yourself you might get more out of it.

As for your issue: you're actually being given a [Draft75](https://github.com/faye/websocket-driver-ruby/blob/master/lib/websocket/driver/draft75.rb) driver, based on the response headers, rather than the `Hybi` driver that modern browsers should use. The decision about which driver to issue is done in [`Websocket::Driver.rack`](https://github.com/faye/websocket-driver-ruby/blob/master/lib/websocket/driver.rb#L147-L156).

If you look at that method, the thing that triggers using the modern driver is the presence of `HTTP_SEC_WEBSOCKET_VERSION` in the Rack env, so I guess you're missing that for some reason.

**Comment by boazsegev** [comment]
I think I found the issue...

Oh - and as I'm writing this, you're pointing it out as well.

`HTTP_SEC_WEBSOCKET_VERSION` is shown by Iodine as `HTTP_SEC-WEBSOCKET-VERSION`... my bad 😖😤 it states in  RFC3875 that `-` should be replaced with `_` - that's what happens when I don't dig deep enough.

As for the replacing EM - that's mostly because it started as a pet project, but now the decision proved to be a big performance boost (as I delay entering the GVL until all the parsing is done) and the API for Iodine is simpler.

As for using the `websocket-driver`, it might not be a bad idea to have an optimized adapter for Faye, but for now I think that having a working version is my higher priority.

**Comment by boazsegev** [comment]
Working :-)

**Comment by boazsegev** [comment]
Thanks a million!

**Comment by jcoglan** [comment]
:tada:
