### ISSUE TITLE
One terminated client connection causes other clients to terminate

### ISSUE THREAD

**Issue by neilberkman** [faye/faye-websocket-ruby#89]
I'm encountering something that may or may not be indicative of an underlying issue in faye-websocket-ruby.  I'll describe the situation in case it's obvious that I'm doing something wrong.  If not I can try to come up with a self-contained test case.

Here's the situation:  I've created a monitoring tool that needs to establish websocket connections to multiple servers.  The monitor for each server consists of a Faye::WebSocket::Client within an EventMachine reactor.  The issue is that if a websocket server dies, the websockets for all of the other monitors are closed as well.  This isn't the case if I just terminate a specific websocket from within my monitoring tool.

If you think this may indicate an issue in faye-websocket-ruby, let me know and I'll extract my code out and also create a server that can be used to reproduce.  And if I'm doing something obviously wrong, I'd really appreciate it if you could give me some guidance.  Thanks!

Update: to be more concise, I guess I should just ask: should it be possible to run multiple faye-websocket-ruby clients within a single ruby process?  Thanks.

**Comment by jcoglan** [comment]
The most likely cause of this is that EventMachine is being stopped when one client disconnects. Within this library, socket instances do not sure any state, the only thing they share is that they need EventMachine to be running at all times.

**Comment by neilberkman** [comment]
Hmm, I'm not explicitly calling `EM.stop`.  I ended up taking another approach to the problem I'm trying to solve.  I'll just close this out since it's likely that the issue was due to something on my end.

**Comment by shashiprab** [comment]
I'm having a similar problem when running with passenger. How do I ensure EM is running always. I too don't call EM.stop - any insights or solutions?
