### ISSUE TITLE
releases from 0.10.0 afterwards doesn't work with websocket-rails

### ISSUE THREAD

**Issue by albertnetymk** [faye/faye-websocket-ruby#91]
It's unclear where the bug locates, in `faye-websocket-ruby` or `websocket-rails`.

The info I have is https://github.com/websocket-rails/websocket-rails/issues/388 and https://github.com/websocket-rails/websocket-rails/issues/404, and the latter contains a link to bare rails app using `websocket-rails` with `faye-websocket-ruby` 0.10.3. The problem could be fixed as the first issue suggested, downgrading `faye-websocket-ruby` to 0.10.0

I had a quick look at changelog, and where `faye` is used in `websocket-rails`, but nothing suspicious.

**Comment by jcoglan** [comment]
In 29f1668e41e0ace7df8142abc2977d0ab3750dc2, the call to start the parser was moved into the `rack_response` method to fix #74. It doesn't appear that you're calling `Faye::WebSocket#rack_response` anywhere in your code, which is why the parser isn't being started.

**Comment by jcoglan** [comment]
@albertnetymk Did my last comment make sense? Should I close this issue or do you have further questions?

**Comment by albertnetymk** [comment]
Thank you for the explanation.

**Comment by phlegx** [comment]
Solved in pull request websocket-rails/websocket-rails#430!
