### ISSUE TITLE
Client :message event experiencing long delays due to EM quantum

### ISSUE THREAD

**Issue by schrockwell** [faye/faye-websocket-ruby#92]
I'm using Faye::WebSocket for the client (v0.10.2) and server (v0.10.0), both running locally on my OS X machine.

When a message is sent from the server, it takes a long time before the :message event is fired in the client. I've discovered this is directly related to the EventMachine quantum parameter. E.g. if the client calls `EM.set_quantum(5000)`, messages take 5 seconds to appear. The delay appears to be on the receiving end, not the sending end. If many messages are sent quickly, then they all flood in at once after the delay.

It's a pretty vanilla client implementation:
```ruby
EM.run do
  @client = Faye::WebSocket::Client.new(url)

  @client.on :open do |event|
    # ...
  end

  @client.on :close do |event|
    # ...
  end

  @client.on :message do |event|
    puts event.data
    # ...
  end
end
```

The server is just calling `#send` on the WebSocket, which was accepted through a Thin server.

From my rudimentary understanding of EventMachine, it would appear that EM is waiting on some other file descriptor in the event loop, and it basically "times out" if nothing happens after the quantum has elapsed. This appears to be blocking the WebSocket data from making it through the reactor right away.

I tried explicitly enabling `EM.kqueue` but that did not make a difference.

I'd like to provide more information but I don't know where to go from here. Can I somehow see which file descriptors EM is iterating over?

**Comment by schrockwell** [comment]
**Problem found!** There was a conflict with the `bunny` gem (RabbitMQ client).

After creating a RabbitMQ queue on the server, I was attempting to pass messages directly from the queue to the WebSocket client like so:

```ruby
# On server
@queue.subscribe do |delivery_info, properties, payload|
  @websocket.send(payload)
end
```

The `bunny` gem does not depend on EventMachine at all, so I'm not sure exactly what was going on here, but the fix was adding an `EM.defer` block on the server. Something in the queue subscription must have been holding up the EM reactor, and deferring the `#send` bypasses this. I don't know why changing the quantum on the client would affect this, but there you go.

```ruby
@queue.subscribe do |delivery_info, properties, payload|
  EM.defer do
    @websocket.send(payload)
  end
end
```

I will leave this issue open, and welcome any insight as to why this is happening. Please close it if there is no real issue here.

**Comment by jcoglan** [comment]
It's quite possible that the delay is down to the thread you were calling `@websocket.send` on. I'm not familiar with bunny so I don't know how it triggers those subscription blocks, but if you're interacting with an EventMachine library then using `EM.defer` (which schedules the block on EM's thread pool) or `EM.next_tick` (which schedules it on the main reactor thread) is a good idea.
