### ISSUE TITLE
Websocket on Tomcat: Unexpected Response Code 200

### ISSUE THREAD

**Issue by awsk1994** [faye/faye-websocket-ruby#95]
Hi, 

I use jRuby and I have the dev environment working fine on Puma server, and websockets work fine. On production, however, the application is deployed on Tomcat using warble. The websocket client gives 

> Websocket connection to <server_ip:port> failed: Error during WebSocket handshake: unexpected response code: 200

In the server log, I could see the onOpen Being triggered, but the websocket connection is lost. 

Can you please help me?

Thanks,
Alex

**Comment by jcoglan** [comment]
If you're getting a 200 status, this suggests that this library is not being given direct access to the TCP stream so it can write its own response headers.

We only support servers that implement the [rack.hijack](http://www.rubydoc.info/github/rack/rack/file/SPEC#Hijacking) API. Does Tomcat support that?

**Comment by awsk1994** [comment]
I realize that this is the same issue as https://github.com/jruby/jruby-rack/issues/167 

Thank you so much for the help.

**Comment by rodolfospalenza** [comment]
Hello @awsk1994, how are you?

Can you use jruby, faye-websocket and warble? I created a war with warble but when I try connect with jetty I receive this message.

```javascript
var scheme   = "ws://";
var uri = scheme + window.document.location.host;
var ws = new WebSocket(uri);

// WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 500
```

I think that I need some jetty configurations when I will create a war. But, I don't know how add this configurations. Is it possible?

This is my issue in warbler gem: https://github.com/jruby/warbler/issues/416

Thanks.
