### ISSUE TITLE
How to use reactor with websockets server?

### ISSUE THREAD

**Issue by tcwitte** [faye/faye-websocket-ruby#96]
Hi,
How can I add work to the reactor thread of a Rack websockets server? I would like to do e.g.
 `EM.add_periodic_timer(1) {puts 'Test'}`
but not in the context of a request but in the context of the whole server. So in this case, it would print Test every second, independent of the number of active websocket connections.

If I do this before or after the App lambda, EventMachine will complain that it's not initialized yet. Within the lambda it's scoped to the request.

(What I want to build is a server that handles websocket connections and TCP connections and acts as a broker between them.)

Thanks in advance!

Kind regards,
Taco

**Comment by jcoglan** [comment]
I'm not really sure what you're asking for but it sounds a bit similar to things I usually handle using classes. Instead of a lambda for your app, I use a class:

```rb
class App
  def initialize
    @timer = EM.add_periodic_timer(1) { ... }
  end

  def call(env)
    # handle WS connection
  end
end
```

If you need to start EventMachine without blocking, you can do something like this:

```rb
Thread.new { EventMachine.run } unless EventMachine.reactor_running?
Thread.pass until EventMachine.reactor_running?
```

**Comment by tcwitte** [comment]
Thanks, that works. Now I understand it a bit better. I've changed it a bit and I'm now using this as a basis for the server:

```
# app.rb
require 'faye/websocket'
Faye::WebSocket.load_adapter('thin')

App = lambda do |env|
  if Faye::WebSocket.websocket?(env)
    ws = Faye::WebSocket.new(env)

    ws.on :message do |event|
      ws.send(event.data)
    end

    ws.on :close do |event|
      p [:close, event.code, event.reason]
      ws = nil
    end

    # Return async Rack response
    ws.rack_response
  else
    # Normal HTTP request
    [200, {'Content-Type' => 'text/plain'}, ['Hello']]
  end
end

EventMachine.run do
  @timer = EM.add_periodic_timer(1) {puts "Time is #{Time.now}\n"}
  thin = Rack::Handler.get('thin')
  thin.run(App, :Port => 8080)
  Signal.trap("INT") {EventMachine.stop}
end
```
