### ISSUE TITLE
faye-websocket convert my Nginx with passenger to serve only one request which block concurrent executions

### ISSUE THREAD

**Issue by MoatazAbdallh** [faye/faye-websocket-ruby#99]
we have used following tune 
if defined?(PhusionPassenger)
  PhusionPassenger.advertised_concurrency_level = 0
end
but server turned to single thread only serving one request per time, so is there are anything missing to avoid this issue?
Regards

**Comment by jcoglan** [comment]
I would consult the [Passenger documentation](https://www.phusionpassenger.com/library/config/nginx/tuning_sse_and_websockets/) and let me know if that doesn't fix your problem.

**Comment by jcoglan** [comment]
Did the link I posted fix your problem? Should I close this issue?

**Comment by jcoglan** [comment]
I'm going to close this due to lack of feedback, but please do re-open it if you have further questions :)
